# Generated by Django 5.1.4 on 2025-01-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrowing",
            unique_together={("borrow_date", "actual_return_date")},
        ),
    ]
