# Generated by Django 5.1.4 on 2025-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_alter_borrowing_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
