# Generated by Django 5.1.4 on 2025-01-03 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_inventory"),
        ("borrowings", "0004_alter_borrowing_borrow_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrowing",
            unique_together={("user", "book")},
        ),
    ]
